from django.conf.urls import patterns, include, url
from django.conf import settings

urlpatterns =  patterns('interface.views',
    url(r'^$', 'home', {}, name='home'),
    url(r'^styleboard/$', 'styleboard', {}, name='styleboard'),
    url(r'^styleboard2/$', 'styleboard2', {}, name='styleboard2'),
    url(r'^styleboard/(?P<cat_id>\d+)$', 'styleboard', {}, name='styleboard_cat'),
    url(r'^styleboard_ajax/$', 'styleboard_ajax', {}, name='styleboard_ajax'),
    url(r'^styleboard_product_ajax/$', 'styleboard_product_ajax', {}, name='styleboard_product_ajax'),    
    url(r'^get_category_tree_ajax/$', 'get_category_tree_ajax', {}, name='get_category_tree_ajax'),
    url(r'^get_product_original_image/$', 'get_product_original_image', {}, name='get_product_original_image'),
    url(r'^styleboard_ajax/product_detail$', 'get_product_details', {}, name='get_product_details'),    
    url(r'^crop/(?P<id>.*)$', 'crop', {}, name='crop'),
    url(r'^crop_view/$', 'crop_view', {}, name='crop_view'),
    url(r'^cropped/$', 'cropped', {}, name='cropped'),
    url(r'^set_product_positions/$', 'set_product_positions', {}, name='set_product_positions'),
    url(r'^search_suggestions/$', 'search_suggestions', {}, name='search_suggestions'),
    url(r'^search_products/$', 'search_products', {}, name='search_products'),
    url(r'^generate_text/$', 'generate_text', {}, name='generate_text'),
    url(r'^generate_embellishment/$', 'generate_embellishment', {}, name='generate_embellishment'),
    url(r'^styleboard/new$', 'new_styleboard', {}, name='new_styleboard'),
    url(r'^styleboard/embellishment_items$', 'get_embellishment_items', {}, name='get_embellishment_items'),
    url(r'^styleboard/get_cart_items$', 'get_personalize_cart_items', {}, name='get_personalize_cart_items'),
    url(r'^set_password_user/$', 'set_password_user', {}, name='set_password_user'),    
    url(r'^styleboard/template_details/$', 'get_template_details', {}, name='get_template_details'),
)