Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'United States of America','US','+1','840', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'HongKong','HK','+852','344', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Philippines','PH','+63', '608', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Afghanistan','AF','+93','004', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Aland Islands','AX','+358','248', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Albania','AL','+355','008', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Algeria','DZ','+213','012', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'American Samoa','AS','+1684','016', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Andorra','AD','+376','020', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Angola','AO','+244','024', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Anguilla','AI','+1264','660', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Antigua and Barbuda','AG','+1268','028', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Argentina','AR','+54','032', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Armenia','AM','+374','051', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Aruba','AW','+297','533', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Australia','AU','+61','036', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Austria','AT','+43','040', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Azerbaijan','AZ','+994','031', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Bahamas','BS','+1242','044', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Bahrain','BH','+973','048', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Bangladesh','BD','+880','050', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Barbados','BB','+1246','052', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Belarus','BY','+375','112', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Belgium','BE','+32','056', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Belize','BZ','+501','084', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Benin','BJ','+229','204', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Bermuda','BM','+1441','060', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Bhutan','BT','+975','064', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Bolivia','BO','+591','068', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Bonaire, Saint Eustatius and Saba','BQ','+5997','535', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Bosnia and Herzegovina','BA','+387','070', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Botswana','BW','+267','072', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Brazil','BR','+55','076', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'British Virgin Islands','VG','+1284','092', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Brunei Darussalam','BN','+673','096', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Bulgaria','BG','+359','100', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Burkina Faso','BF','+226','854', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Burundi','BI','+257','108', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Cambodia','KH','+855','116', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Cameroon','CM','+237','120', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Canada','CA','+1','124', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Cape Verde','CV','+238','132', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Cayman Islands','KY','+1345','136', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Central African Republic','CF','+236','140', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Chad','TD','+235','148', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Chile','CL','+56','152', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'China','CN','+86','156', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'China, Macao Special Administrative Region','MO','+853','446', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Colombia','CO','+57','170', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Comoros','KM','+269','174', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Congo','CG','+242','178', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Cook Islands','CK','+682','184', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Costa Rica','CR','+506','188', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Cote d''Ivoire','CI','+225','384', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Croatia','HR','+385','191', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Cuba','CU','+53','192', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Curacao','CW','+5999','531', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Cyprus','CY','+357','196', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Czech Republic','CZ','+420','203', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Democratic People''s Republic of Korea','KP','+82','408', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Democratic Republic of the Congo','CD','+242','180', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Denmark','DK','+45','208', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Djibouti','DJ','+253','262', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Dominica','DM','+1767','212', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Dominican Republic','DO','+849','214', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Ecuador','EC','+593','218', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Egypt','EG','+20','818', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'El Salvador','SV','+503','222', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Equatorial Guinea','GQ','+240','226', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Eritrea','ER','+291','232', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Estonia','EW','+372','233', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Ethiopia','ET','+251','231', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Faeroe Islands','FO','+298','234', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Falkland Islands','FK','+500','238', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Fiji','FJ','+679','242', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Finland','FI','+358','246', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'France','FR','+33','250', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'French Guiana','GF','+594','254', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'French Polynesia','PF','+689','258', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Gabon','GA','+241','266', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Gambia','GM','+220','270', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Georgia','GE','+995','268', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Germany','DE','+49','276', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Ghana','GH','+233','288', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Gibraltar','GI','+350','292', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Greece','GR','+30','300', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Greenland','GL','+299','304', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Grenada','GD','+1473','308', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Guadeloupe','GP','+590','312', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Guam','GU','+1671','316', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Guatemala','GT','+502','320', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Guernsey','GG','+44','831', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Guinea','GN','+224','324', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Guinea-Bissau','GW','+245','624', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Guyana','GY','+592','328', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Haiti','HT','+509','332', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Holy See','VA','+379','336', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Honduras','HN','+504','340', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Hungary','HU','+36','348', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Iceland','IS','+354','352', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'India','IN','+91','356', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Indonesia','ID','+62','360', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Iran','IR','+98','364', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Iraq','IQ','+964','368', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Ireland','IE','+353','372', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Isle of Man','IM','+44','833', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Israel','IL','+972','376', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Italy','IT','+39','380', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Jamaica','JM','+1876','388', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Japan','JP','+81','392', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Jersey','JE','+44','832', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Jordan','JO','+962','400', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Kazakhstan','KZ','+77','398', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Kenya','KE','+254','404', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Kiribati','KI','+686','296', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Kuwait','KW','+965','414', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Kyrgyzstan','KG','+996','417', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Lao People''s Democratic Republic','LA','+856','418', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Latvia','LV','+371','428', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Lebanon','LB','+961','422', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Lesotho','LS','+266','426', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Liberia','LR','+231','430', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Libyan Arab Jamahiriya','LY','+218','434', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Liechtenstein','LI','+423','438', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Lithuania','LT','+370','440', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Luxembourg','LU','+352','442', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Madagascar','MG','+261','450', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Malawi','MW','+265','454', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Malaysia','MY','+60','458', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Maldives','MV','+960','462', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Mali','ML','+223','466', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Malta','MT','+356','470', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Marshall Islands','MH','+692','584', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Martinique','MQ','+596','474', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Mauritania','MR','+222','478', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Mauritius','MU','+230','480', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Mayotte','YT','+262','175', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Mexico','MX','+52','484', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Micronesia','FM','+691','583', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Monaco','MC','+377','492', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Mongolia','MN','+976','496', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Montenegro','ME','+382','499', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Montserrat','MS','+1664','500', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Morocco','MA','+212','504', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Mozambique','MZ','+258','508', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Myanmar','MM','+95','104', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Namibia','NA','+264','516', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Nauru','NR','+674','520', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Nepal','NP','+977','524', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Netherlands','NL','+31','528', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'New Caledonia','NC','+687','540', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'New Zealand','NZ','+64','554', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Nicaragua','NI','+505','558', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Niger','NE','+227','562', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Nigeria','NG','+234','566', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Niue','NU','+683','570', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Norfolk Island','NF','+672','574', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Northern Mariana Islands','MP','+1670','580', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Norway','NO','+47','578', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Occupied Palestinian Territory','PS','+970','275', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Oman','OM','+963','512', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Pakistan','PK','+92','586', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Palau','PW','+680','585', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Panama','PA','+507','591', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Papua New Guinea','PG','+675','598', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Paraguay','PY','+595','600', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Peru','PE','+51','604', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Pitcairn','PN','+64','612', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Poland','PL','+48','616', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Portugal','PT','+351','620', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Puerto Rico','PR','+1939','630', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Qatar','QA','+974','634', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Republic of Korea','KR','+82','410', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Republic of Moldova','MD','+373','498', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Reunion','RE','+262','638', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Romania','RO','+40','642', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Russian Federation','RU','+7','643', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Rwanda','RW','+250','646', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Saint-Barthelemy','BL','+590','652', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Saint Helena','SH','+290','654', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Saint Kitts and Nevis','KN','+1869','659', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Saint Lucia','LC','+1758','662', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Saint-Martin','MF','+590','663', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Saint Pierre and Miquelon','PM','+508','666', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Saint Vincent and the Grenadines','VC','+1784','670', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Samoa','WS','+685','882', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'San Marino','SM','+378','674', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Sao Tome and Principe','ST','+239','678', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Saudi Arabia','SA','+966','682', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Senegal','SN','+221','686', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Serbia','RS','+381','688', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Seychelles','SC','+248','690', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Sierra Leone','SL','+232','694', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Singapore','SG','+65','702', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Sint Maarten','SX','+5995','534', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Slovakia','SK','+421','703', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Slovenia','SI','+386','705', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Solomon Islands','SB','+677','090', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Somalia','SO','+252','706', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'South Africa','ZA','+27','710', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Spain','ES','+34','724', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Sri Lanka','LK','+94','144', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Sudan','SD','+249','729', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Suriname','SR','+597','740', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Svalbard and Jan Mayen Islands','SJ','+47','744', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Swaziland','SZ','+268','748', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Sweden','SE','+46','752', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Switzerland','CH','+41','756', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Syrian Arab Republic','SY','+963','760', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Tajikistan','TJ','+992','762', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Thailand','TH','+66','764', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'The former Yugoslav Republic of Macedonia','MK','+389','807', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Timor-Leste','TL','+670','626', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Togo','TG','+228','768', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Tokelau','TK','+690','772', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Tonga','TO','+676','776', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Trinidad and Tobago','TT','+1868','780', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Tunisia','TN','+216','788', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Turkey','TR','+90','792', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Turkmenistan','TM','+993','795', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Turks and Caicos Islands','TC','+1649','796', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Tuvalu','TV','+688','798', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Uganda','UG','+256','800', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Ukraine','UA','+380','804', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'United Arab Emirates','AE','+971','784', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'United Kingdom of Great Britain and Northern Ireland','GB','+353','826', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'United Republic of Tanzania','TZ','+255','834', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'United States Virgin Islands','VG','+1284','850', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Uruguay','UY','+598','858', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Uzbekistan','UZ','+998','860', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Vanuatu','VU','+678','548', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Venezuela','VE','+58','862', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Vietnam','VN','+84','704', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Wallis and Futuna Islands','WF','+681','876', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Western Sahara','ME','+5289','732', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Yemen','YD','+967','887', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Zambia','ZM','+260','894', 1);
Insert into countries (id,name,code,country_code,iso_numerical_code, is_activated) values (NULL,'Zimbabwe','ZW','+263','716', 1);
