Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'United States of America','US','+1','840');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'HongKong','HK','+852','344');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Philippines','PH','+63', '608');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Afghanistan','AF','+93','004');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Aland Islands','AX','+358','248');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Albania','AL','+355','008');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Algeria','DZ','+213','012');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'American Samoa','AS','+1684','016');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Andorra','AD','+376','020');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Angola','AO','+244','024');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Anguilla','AI','+1264','660');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Antigua and Barbuda','AG','+1268','028');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Argentina','AR','+54','032');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Armenia','AM','+374','051');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Aruba','AW','+297','533');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Australia','AU','+61','036');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Austria','AT','+43','040');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Azerbaijan','AZ','+994','031');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Bahamas','BS','+1242','044');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Bahrain','BH','+973','048');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Bangladesh','BD','+880','050');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Barbados','BB','+1246','052');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Belarus','BY','+375','112');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Belgium','BE','+32','056');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Belize','BZ','+501','084');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Benin','BJ','+229','204');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Bermuda','BM','+1441','060');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Bhutan','BT','+975','064');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Bolivia','BO','+591','068');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Bonaire, Saint Eustatius and Saba','BQ','+5997','535');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Bosnia and Herzegovina','BA','+387','070');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Botswana','BW','+267','072');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Brazil','BR','+55','076');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'British Virgin Islands','VG','+1284','092');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Brunei Darussalam','BN','+673','096');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Bulgaria','BG','+359','100');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Burkina Faso','BF','+226','854');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Burundi','BI','+257','108');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Cambodia','KH','+855','116');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Cameroon','CM','+237','120');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Canada','CA','+1','124');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Cape Verde','CV','+238','132');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Cayman Islands','KY','+1345','136');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Central African Republic','CF','+236','140');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Chad','TD','+235','148');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Chile','CL','+56','152');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'China','CN','+86','156');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'China, Macao Special Administrative Region','MO','+853','446');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Colombia','CO','+57','170');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Comoros','KM','+269','174');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Congo','CG','+242','178');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Cook Islands','CK','+682','184');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Costa Rica','CR','+506','188');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Cote d''Ivoire','CI','+225','384');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Croatia','HR','+385','191');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Cuba','CU','+53','192');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Curacao','CW','+5999','531');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Cyprus','CY','+357','196');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Czech Republic','CZ','+420','203');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Democratic People''s Republic of Korea','KP','+82','408');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Democratic Republic of the Congo','CD','+242','180');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Denmark','DK','+45','208');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Djibouti','DJ','+253','262');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Dominica','DM','+1767','212');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Dominican Republic','DO','+849','214');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Ecuador','EC','+593','218');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Egypt','EG','+20','818');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'El Salvador','SV','+503','222');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Equatorial Guinea','GQ','+240','226');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Eritrea','ER','+291','232');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Estonia','EW','+372','233');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Ethiopia','ET','+251','231');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Faeroe Islands','FO','+298','234');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Falkland Islands','FK','+500','238');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Fiji','FJ','+679','242');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Finland','FI','+358','246');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'France','FR','+33','250');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'French Guiana','GF','+594','254');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'French Polynesia','PF','+689','258');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Gabon','GA','+241','266');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Gambia','GM','+220','270');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Georgia','GE','+995','268');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Germany','DE','+49','276');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Ghana','GH','+233','288');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Gibraltar','GI','+350','292');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Greece','GR','+30','300');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Greenland','GL','+299','304');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Grenada','GD','+1473','308');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Guadeloupe','GP','+590','312');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Guam','GU','+1671','316');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Guatemala','GT','+502','320');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Guernsey','GG','+44','831');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Guinea','GN','+224','324');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Guinea-Bissau','GW','+245','624');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Guyana','GY','+592','328');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Haiti','HT','+509','332');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Holy See','VA','+379','336');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Honduras','HN','+504','340');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Hungary','HU','+36','348');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Iceland','IS','+354','352');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'India','IN','+91','356');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Indonesia','ID','+62','360');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Iran','IR','+98','364');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Iraq','IQ','+964','368');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Ireland','IE','+353','372');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Isle of Man','IM','+44','833');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Israel','IL','+972','376');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Italy','IT','+39','380');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Jamaica','JM','+1876','388');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Japan','JP','+81','392');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Jersey','JE','+44','832');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Jordan','JO','+962','400');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Kazakhstan','KZ','+77','398');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Kenya','KE','+254','404');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Kiribati','KI','+686','296');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Kuwait','KW','+965','414');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Kyrgyzstan','KG','+996','417');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Lao People''s Democratic Republic','LA','+856','418');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Latvia','LV','+371','428');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Lebanon','LB','+961','422');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Lesotho','LS','+266','426');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Liberia','LR','+231','430');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Libyan Arab Jamahiriya','LY','+218','434');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Liechtenstein','LI','+423','438');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Lithuania','LT','+370','440');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Luxembourg','LU','+352','442');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Madagascar','MG','+261','450');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Malawi','MW','+265','454');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Malaysia','MY','+60','458');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Maldives','MV','+960','462');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Mali','ML','+223','466');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Malta','MT','+356','470');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Marshall Islands','MH','+692','584');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Martinique','MQ','+596','474');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Mauritania','MR','+222','478');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Mauritius','MU','+230','480');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Mayotte','YT','+262','175');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Mexico','MX','+52','484');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Micronesia','FM','+691','583');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Monaco','MC','+377','492');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Mongolia','MN','+976','496');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Montenegro','ME','+382','499');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Montserrat','MS','+1664','500');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Morocco','MA','+212','504');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Mozambique','MZ','+258','508');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Myanmar','MM','+95','104');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Namibia','NA','+264','516');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Nauru','NR','+674','520');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Nepal','NP','+977','524');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Netherlands','NL','+31','528');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'New Caledonia','NC','+687','540');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'New Zealand','NZ','+64','554');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Nicaragua','NI','+505','558');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Niger','NE','+227','562');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Nigeria','NG','+234','566');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Niue','NU','+683','570');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Norfolk Island','NF','+672','574');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Northern Mariana Islands','MP','+1670','580');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Norway','NO','+47','578');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Occupied Palestinian Territory','PS','+970','275');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Oman','OM','+963','512');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Pakistan','PK','+92','586');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Palau','PW','+680','585');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Panama','PA','+507','591');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Papua New Guinea','PG','+675','598');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Paraguay','PY','+595','600');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Peru','PE','+51','604');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Pitcairn','PN','+64','612');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Poland','PL','+48','616');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Portugal','PT','+351','620');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Puerto Rico','PR','+1939','630');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Qatar','QA','+974','634');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Republic of Korea','KR','+82','410');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Republic of Moldova','MD','+373','498');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Reunion','RE','+262','638');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Romania','RO','+40','642');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Russian Federation','RU','+7','643');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Rwanda','RW','+250','646');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Saint-Barthelemy','BL','+590','652');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Saint Helena','SH','+290','654');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Saint Kitts and Nevis','KN','+1869','659');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Saint Lucia','LC','+1758','662');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Saint-Martin','MF','+590','663');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Saint Pierre and Miquelon','PM','+508','666');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Saint Vincent and the Grenadines','VC','+1784','670');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Samoa','WS','+685','882');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'San Marino','SM','+378','674');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Sao Tome and Principe','ST','+239','678');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Saudi Arabia','SA','+966','682');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Senegal','SN','+221','686');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Serbia','RS','+381','688');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Seychelles','SC','+248','690');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Sierra Leone','SL','+232','694');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Singapore','SG','+65','702');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Sint Maarten','SX','+5995','534');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Slovakia','SK','+421','703');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Slovenia','SI','+386','705');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Solomon Islands','SB','+677','090');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Somalia','SO','+252','706');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'South Africa','ZA','+27','710');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Spain','ES','+34','724');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Sri Lanka','LK','+94','144');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Sudan','SD','+249','729');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Suriname','SR','+597','740');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Svalbard and Jan Mayen Islands','SJ','+47','744');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Swaziland','SZ','+268','748');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Sweden','SE','+46','752');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Switzerland','CH','+41','756');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Syrian Arab Republic','SY','+963','760');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Tajikistan','TJ','+992','762');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Thailand','TH','+66','764');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'The former Yugoslav Republic of Macedonia','MK','+389','807');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Timor-Leste','TL','+670','626');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Togo','TG','+228','768');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Tokelau','TK','+690','772');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Tonga','TO','+676','776');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Trinidad and Tobago','TT','+1868','780');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Tunisia','TN','+216','788');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Turkey','TR','+90','792');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Turkmenistan','TM','+993','795');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Turks and Caicos Islands','TC','+1649','796');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Tuvalu','TV','+688','798');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Uganda','UG','+256','800');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Ukraine','UA','+380','804');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'United Arab Emirates','AE','+971','784');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'United Kingdom of Great Britain and Northern Ireland','GB','+353','826');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'United Republic of Tanzania','TZ','+255','834');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'United States Virgin Islands','VG','+1284','850');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Uruguay','UY','+598','858');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Uzbekistan','UZ','+998','860');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Vanuatu','VU','+678','548');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Venezuela','VE','+58','862');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Vietnam','VN','+84','704');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Wallis and Futuna Islands','WF','+681','876');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Western Sahara','ME','+5289','732');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Yemen','YD','+967','887');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Zambia','ZM','+260','894');
Insert into countries (id,name,code,country_code,iso_numerical_code) values (NULL,'Zimbabwe','ZW','+263','716');
